# Generated by Django 4.1.1 on 2022-09-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_category_alter_listing_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='nodesc', max_length=1024),
            preserve_default=False,
        ),
    ]
