# Generated by Django 4.1.1 on 2022-09-19 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watched_by',
            field=models.ManyToManyField(related_name='user_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
