# Generated by Django 4.1.1 on 2022-09-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.IntegerField(default=28),
            preserve_default=False,
        ),
    ]
