# Generated by Django 4.1.1 on 2022-09-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bid_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='creator',
        ),
    ]
