# Generated by Django 4.1.1 on 2022-09-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.FloatField(),
        ),
    ]
