# Generated by Django 4.1.1 on 2022-09-20 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_bid_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watched_by',
            field=models.ManyToManyField(blank=True, related_name='user_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
